import { Providers } from "./GlobalRedux/provider";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Container from "./components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Container>
            <Navbar />
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
